-- =========================================================
-- Smart Farm IoT Monitoring Database Schema & Realtime Setup
-- =========================================================

-- 1. ตารางลงทะเบียน Node สำหรับเชื่อมโยงกับผู้ใช้งาน (Owner)
CREATE TABLE IF NOT EXISTS public.nodes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    owner_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    mac_address VARCHAR(17) UNIQUE NOT NULL,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. ตารางเก็บบันทึกข้อมูล Telemetry ที่ส่งมาจาก ESP32 ผ่าน Gateway
CREATE TABLE IF NOT EXISTS public.telemetry_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mac_address VARCHAR(17) NOT NULL REFERENCES public.nodes(mac_address) ON DELETE CASCADE,
    battery_voltage NUMERIC(4, 2) NOT NULL, -- เช่น 3.55 V
    surface_temp NUMERIC(5, 1) NOT NULL,    -- เช่น 28.5 C
    air_temp NUMERIC(5, 1) NOT NULL,        -- เช่น 31.2 C
    air_humidity NUMERIC(5, 1) NOT NULL,    -- เช่น 65.5 %RH
    ambient_light INTEGER NOT NULL,          -- เช่น 1250 Lux
    npk_n INTEGER NOT NULL,                 -- mg/kg
    npk_p INTEGER NOT NULL,                 -- mg/kg
    npk_k INTEGER NOT NULL,                 -- mg/kg
    rssi INTEGER,                           -- LoRa Signal Strength (dBm)
    snr NUMERIC(4, 1),                      -- LoRa Signal-to-Noise Ratio (dB)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Index สำหรับค้นหาประวัติย้อนหลังตาม MAC Address และเวลา
CREATE INDEX IF NOT EXISTS idx_telemetry_mac_created ON public.telemetry_logs (mac_address, created_at DESC);

-- 3. เปิดใช้งาน Row Level Security (RLS)
ALTER TABLE public.nodes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.telemetry_logs ENABLE ROW LEVEL SECURITY;

-- 4. RLS Policies:
-- ผู้ใช้ดูและจัดการได้เฉพาะ Node ของตนเอง
CREATE POLICY "Users can view own nodes"
ON public.nodes FOR SELECT
USING (auth.uid() = owner_id);

CREATE POLICY "Users can insert own nodes"
ON public.nodes FOR INSERT
WITH CHECK (auth.uid() = owner_id);

-- ผู้ใช้ดูข้อมูล Telemetry ได้เฉพาะของ Node ที่ตนเองเป็นเจ้าของ
CREATE POLICY "Users can view telemetry from owned nodes"
ON public.telemetry_logs FOR SELECT
USING (
    EXISTS (
        SELECT 1 FROM public.nodes
        WHERE public.nodes.mac_address = public.telemetry_logs.mac_address
        AND public.nodes.owner_id = auth.uid()
    )
);

-- 5. เปิดใช้งาน Supabase Realtime บนตาราง telemetry_logs
-- คำสั่งนี้จะอนุญาตให้ตาราง telemetry_logs ส่ง Logical Replication Event ผ่าน WebSocket ทันทีที่มีการ INSERT
ALTER PUBLICATION supabase_realtime ADD TABLE public.telemetry_logs;
